core:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/.vitepress/**'
          - 'pests-repellent/**'
          - 'scripts/**'
          - 'api/**'
          - '*'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*.md'
